version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "mysqldb"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "user123"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network: 
    name: mysql_net
    driver: bridge

