version: '3.3'

services:
  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_microservicio 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ejemplo.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"