apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: ms2-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms2-prod
    spec:
      containers:
      - name: ms2-prod
        image: "tgcoriast/ms2:1.0-build${buildNumber}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred


